Repository geekganization/MOUP, pull requests merged in 2025-06, with the labels that each got.

#6 마이페이지 UI 구현 완료
  Routory/Routory/Presentation/MyPage/View/InfoView.swift
  Routory/Routory/Presentation/MyPage/View/MyPageMenuListView.swift
  Routory/Routory/Presentation/MyPage/View/MyPageNavigationBar.swift
  Routory/Routory/Presentation/MyPage/View/MyPageTableViewCell.swift
  Routory/Routory/Presentation/MyPage/View/MyPageView.swift
  Routory/Routory/Presentation/MyPage/ViewController/InfoViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/BackButton.imageset/BackButton.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/BackButton.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRight.imageset/ChevronRight.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRight.imageset/Contents.json
Labels: enhancement

#8 구글 로그인 / 회원가입 UI 및 로직 구현
  .gitignore
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/App/AppDelegate.swift
  Routory/Routory/App/SceneDelegate.swift
  Routory/Routory/Data/Repositories/UserRepository.swift
  Routory/Routory/Data/Services/GoogleAuthService.swift
  Routory/Routory/Data/Services/Service.swift
  Routory/Routory/Data/Services/UserService.swift
  Routory/Routory/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/RegisterUserUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/RegisterUserUseCase.swift
  Routory/Routory/Presentation/Login/View/LoginView.swift
  Routory/Routory/Presentation/Login/View/LoginViewController.swift
  Routory/Routory/Presentation/Login/ViewModel/LoginViewModel.swift
  Routory/Routory/Presentation/Signup/View/CardButton.swift
  Routory/Routory/Presentation/Signup/View/CustomDialogView.swift
  Routory/Routory/Presentation/Signup/View/SignupView.swift
  Routory/Routory/Presentation/Signup/View/SignupViewController.swift
  Routory/Routory/Presentation/Signup/ViewModel/SignupViewModel.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/ios_light_sq_SU.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/ios_light_sq_SU@2x.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/ios_light_sq_SU@3x.png
  Routory/Routory/Resources/Info.plist
Labels: enhancement

#27 Feat/#19
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/Data/Repositories/RoutineRepository.swift
  Routory/Routory/Data/Repositories/UserRepository.swift
  Routory/Routory/Data/Services/GoogleAuthService.swift
  Routory/Routory/Data/Services/RoutineService.swift
  Routory/Routory/Data/Services/UserService.swift
  Routory/Routory/Domain/Entities/CalendarEvent.swift
  Routory/Routory/Domain/Entities/Routine.swift
  Routory/Routory/Domain/Entities/User.swift
  Routory/Routory/Domain/Entities/UserWorkplace.swift
  Routory/Routory/Domain/Entities/WorkCalendar.swift
  Routory/Routory/Domain/Entities/WorkerDetail.swift
  Routory/Routory/Domain/Entities/Workplace.swift
  Routory/Routory/Domain/Interfaces/Repositories/RoutineRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/RoutineUseCaseProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/UserUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/RoutineUseCase.swift
  Routory/Routory/Domain/UseCases/UserUseCase.swift
  Routory/Routory/Presentation/Login/View/LoginViewController.swift
  Routory/Routory/Presentation/Login/ViewModel/LoginViewModel.swift
  Routory/Routory/Presentation/Signup/View/SignupView.swift
  Routory/Routory/Presentation/Signup/ViewModel/SignupViewModel.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Frame 1464204142.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Frame 1464204142@2x.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Frame 1464204142@3x.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/ios_light_sq_SU.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/ios_light_sq_SU@2x.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/ios_light_sq_SU@3x.png
Labels: enhancement

#29 알바생 기준 초대 코드로 근무지 등록 UI 구현
  Routory/Routory/Presentation/Home/View/HomeHeaderView.swift
  Routory/Routory/Presentation/Home/View/InviteCodeView.swift
  Routory/Routory/Presentation/Home/View/WorkplaceAddModalView.swift
  Routory/Routory/Presentation/Home/View/WorkplaceListTableViewCell.swift
  Routory/Routory/Presentation/Home/View/WorkplaceListView.swift
  Routory/Routory/Presentation/Home/View/WorkplaceSearchResultView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceListViewController.swift
  Routory/Routory/Presentation/MyPage/View/EditModal.swift
  Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountModalViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/EditModalViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Colors/Modal/ModalBackground.colorset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Calendar.imageset/Calendar.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Calendar.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Mail.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Mail.imageset/Mail.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Plus.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Plus.imageset/Plus.svg
Labels: enhancement

#37 캘린더 UI 구현
  Routory/Routory/Domain/Entities/UserWorkplace.swift
  Routory/Routory/Presentation/Calendar/Utils/CalendarMode.swift
  Routory/Routory/Presentation/Calendar/Utils/CalendarRange.swift
  Routory/Routory/Presentation/Calendar/Utils/PickerViewComponents.swift
  Routory/Routory/Presentation/Calendar/View/CalendarEventListView.swift
  Routory/Routory/Presentation/Calendar/View/CalendarView.swift
  Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
  Routory/Routory/Presentation/Calendar/View/Cell/EventCell.swift
  Routory/Routory/Presentation/Calendar/View/Cell/WorkplaceCell.swift
  Routory/Routory/Presentation/Calendar/View/Components/CalendarHeaderView.swift
  Routory/Routory/Presentation/Calendar/View/Components/ColorBorderView.swift
  Routory/Routory/Presentation/Calendar/View/Components/GrabberView.swift
  Routory/Routory/Presentation/Calendar/View/Components/OtherEventLabel.swift
  Routory/Routory/Presentation/Calendar/View/FilterView.swift
  Routory/Routory/Presentation/Calendar/View/YearMonthPickerView.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarEventListViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/CalendarEventListVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/RegistrationVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/YearMonthPickerVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/FilterViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/YearMonthPickerViewController.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Colors/KakaoLogin/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Colors/KakaoLogin/KakaoBackground.colorset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Colors/KakaoLogin/KakaoTextColor.colorset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/BackButton.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Chevron/ChevronRight.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Calendar.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Mail.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/NewWorkplace/Plus.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/KakaoLogin/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/KakaoLogin/KakaoLogo.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/KakaoLogin/KakaoLogo.imageset/KakaoLogo.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/KakaoLogin/kakao_login_medium_wide.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/KakaoLogin/kakao_login_medium_wide.imageset/kakao_login_medium_wide.png
  Routory/Routory/Resources/Assets.xcassets/Icons/MyPage/EditButton.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/MyPage/XMark.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Plus/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Plus/Plus.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Plus/Plus.imageset/Plus.svg
  Routory/Routory/Resources/Info.plist
Labels: enhancement

#40 Feat/#32
  Routory/Routory/Presentation/Registration/Components/ValueRowView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewModel/NewRoutineViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RoutineSelection/View/RoutineCell.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RoutineSelection/ViewController/RoutineSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RoutineSelection/ViewModel/RoutineSelectionViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkPlaceSelectionView.swift
Labels: enhancement

#47 Feat/#43
  Routory/Routory/Presentation/Registration/Components/SelectionViewController.swift
  Routory/Routory/Presentation/Registration/Components/TextInputViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/ColorSelection/ViewController/ColorSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/EmployeeSelection /ViewController/EmployeeSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RepeatDays/ViewController/RepeatDaysViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RoutineSelection/ViewController/RoutineSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#49 feat: #48 - 스와이프 안되는 문제 해결
  Routory/Routory/Presentation/Registration/Components/SelectionViewController.swift
  Routory/Routory/Presentation/Registration/Components/TextInputViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/ColorSelection/ViewController/ColorSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/EmployeeSelection /ViewController/EmployeeSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RepeatDays/ViewController/RepeatDaysViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/RoutineSelection/ViewController/RoutineSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: bug

#53 탭바 뷰모델 구현 및 전체 루틴 관리 데이터 fetch 구현
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/App/SceneDelegate.swift
  Routory/Routory/Common/Managers/UserManager.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Login/View/LoginViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
  Routory/Routory/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewController/WorkplaceRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewModel/ManageRoutineViewModel.swift
  Routory/Routory/Presentation/Signup/View/SignupViewController.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabBarViewModel.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
Labels: enhancement

#56 이벤트 일별 / 월별 조회
  Routory/Routory/Data/Repositories/EventRepository.swift
  Routory/Routory/Data/Repositories/Repository.swift
  Routory/Routory/Data/Services/EventService.swift
  Routory/Routory/Domain/Entities/Entity.swift
  Routory/Routory/Domain/Interfaces/Repositories/EventRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/Repositories/RepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/EventUsecaseProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/UseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/EventUseCase.swift
  Routory/Routory/Domain/UseCases/UseCase.swift
Labels: enhancement

#57 애플 로그인 구현
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/App/SceneDelegate.swift
  Routory/Routory/Data/Services/AppleAuthService.swift
  Routory/Routory/Data/Services/DelegateProxies/RxASAuthorizationControllerDelegateProxy.swift
  Routory/Routory/Presentation/Login/View/LoginView.swift
  Routory/Routory/Presentation/Login/View/LoginViewController.swift
  Routory/Routory/Presentation/Login/ViewModel/LoginViewModel.swift
  Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountModalViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Frame 1464204142.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Frame 1464204142@2x.png
  Routory/Routory/Resources/Assets.xcassets/Icons/GoogleLogin/ios_light_sq_SU.imageset/Frame 1464204142@3x.png
  Routory/Routory/Resources/Assets.xcassets/Images/AppleLogin/AppleSignInImage.imageset/AppleSignInImage.png
  Routory/Routory/Resources/Assets.xcassets/Images/AppleLogin/AppleSignInImage.imageset/AppleSignInImage@2x.png
  Routory/Routory/Resources/Assets.xcassets/Images/AppleLogin/AppleSignInImage.imageset/AppleSignInImage@3x.png
  Routory/Routory/Resources/Assets.xcassets/Images/AppleLogin/AppleSignInImage.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/AppleLogin/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/GoogleLogin/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/GoogleLogin/GoogleSignInImage.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/GoogleLogin/GoogleSignInImage.imageset/GoogleSignInImage.png
  Routory/Routory/Resources/Assets.xcassets/Images/GoogleLogin/GoogleSignInImage.imageset/GoogleSignInImage@2x.png
  Routory/Routory/Resources/Assets.xcassets/Images/GoogleLogin/GoogleSignInImage.imageset/GoogleSignInImage@3x.png
  Routory/Routory/Routory.entitlements
Labels: enhancement

#58 홈 내 미완성 기능 일부 구현
  Routory/Routory/Presentation/Components/BaseNavigationBar.swift
  Routory/Routory/Presentation/Home/View/HomeView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Routine/View/Cell/TodaysRoutineCell.swift
  Routory/Routory/Presentation/Routine/View/WorkplaceRoutineView.swift
  Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
Labels: enhancement

#59 신규 근무지 추가 / 근무(이벤트) 추가 로직 구현
  Routory/Routory/Data/Repositories/CalendarRepository.swift
  Routory/Routory/Data/Repositories/WorkplaceRepository.swift
  Routory/Routory/Data/Services/CalendarService.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Interfaces/Repositories/CalendarRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/Repositories/WorkplaceRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/CalendarUseCaseProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/WorkplaceUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/CalendarUseCase.swift
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
Labels: enhancement

#60 PR 누락본
  Routory/Routory/Data/Repositories/WorkplaceRepository.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Interfaces/Repositories/WorkplaceRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/WorkplaceUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
Labels: enhancement

#62 Feat/#61
  Routory/Routory/Data/Repositories/WorkerWorkplaceRepository.swift
  Routory/Routory/Domain/Interfaces/Repositories/WorkerWorkplaceRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/CreateWorkerWorkplaceUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/CreateWorkerWorkplaceUseCase.swift
  Routory/Routory/Presentation/Registration/Components/SelectionViewController.swift
  Routory/Routory/Presentation/Registration/Components/TextInputViewController.swift
  Routory/Routory/Presentation/Registration/Handler/RegistrationActionHandler.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/Handler/WorkplaceRegistrationDelegateHandler.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewModel/CreateWorkplaceViewModel.swift
Labels: enhancement

#66 Feat/#65
  Routory/Routory/Data/Repositories/WorkplaceRepository.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/UseCases/CalendarUseCase.swift
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Handler/ShiftRegistrationDelegateHandler.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkPlaceSelectionView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/OwnerEmployeeShiftRegistrationViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/OwnerSelfShiftRegistrationViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/WorkShiftRegistrationViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/WorkplaceListViewModel.swift
Labels: enhancement

#64 초대코드 기반 근무지 등록 기능 구현
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Presentation/Home/View/WorkplaceListTableViewCell.swift
  Routory/Routory/Presentation/Home/View/WorkplaceListView.swift
  Routory/Routory/Presentation/Home/View/WorkplaceSearchResultView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeEmptyModalViewController.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceListViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/InviteCodeViewModel.swift
  Routory/Routory/Presentation/Registration/Components/ValueRowView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkplaceInfoView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/WorkplaceRegistrationContentView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
Labels: enhancement

#69 Feat/#67
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Handler/ShiftRegistrationDelegateHandler.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/EmployeeSelection /ViewController/EmployeeSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/EmployeeSelection /ViewModel/EmployeeSelectionViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/OwnerEmployeeShiftRegistrationViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/OwnerSelfShiftRegistrationViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/ShiftRegistrationViewModel.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#71 feat: #70 - workConditionView랑 labelView 숨김처리
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#74 초대 코드 생성기 추가
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/Common/Utils/InviteCodeGenerator.swift
  Routory/Routory/Resources/JSON/opensource_license.json
Labels: enhancement

#78 Feat/#75
  Routory/Routory/Common/Managers/UserManager.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#80 로딩 애니메이션 임시 구현 및 근무지 생성 직접 입력 분기 처리
  Routory/Routory/Presentation/Components/LoadingAnimationView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Routine/View/ManageRoutineView.swift
  Routory/Routory/Presentation/Routine/View/WorkplaceRoutineView.swift
  Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewModel/ManageRoutineViewModel.swift
  Routory/Routory/Presentation/Routine/ViewModel/WorkplaceRoutineViewModel.swift
Labels: enhancement

#81 임시 목데이터를 이용해 사장님 매장 셀 testable하게 추가
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Entities/Dummy/DummyStoreInfo.swift
  Routory/Routory/Presentation/Home/View/Cell/MyStoreCell.swift
  Routory/Routory/Presentation/Home/View/Section/HomeTableViewFirstSection.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: bug

#85 feat: #83 - createdBy 코드 부분 수정
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
Labels: enhancement

#88 구현된 Usecase 기반으로 HomeViewModel 데이터 fetch까지 구현
  Routory/Routory/Domain/Entities/Dummy/DummyHomeHeaderInfo.swift
  Routory/Routory/Domain/Entities/Dummy/DummyWorkplaceInfo.swift
  Routory/Routory/Domain/Entities/HomeHeaderInfo.swift
  Routory/Routory/Presentation/Home/View/HomeHeaderView.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
Labels: enhancement

#92 근무지 삭제/ 고정급여 반환 / 회원탈퇴 로직 수정 / 월급일 반환 로직 구현
  Routory/Routory/Data/Repositories/WorkplaceRepository.swift
  Routory/Routory/Data/Services/UserService.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Entities/Workplace.swift
  Routory/Routory/Domain/Interfaces/Repositories/WorkplaceRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/WorkplaceUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
  Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountModalViewController.swift
Labels: enhancement

#90 feat: #89 - 시급 안올라가는 문제 해결
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#96 캘린더 비즈니스 로직 반영
  Routory/Routory/Presentation/Calendar/View/Cell/EventCell.swift
  Routory/Routory/Presentation/Calendar/View/FilterView.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarEventListViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/FilterViewController.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarDayCellViewModel.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarEventListViewModel.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
Labels: enhancement

#106 fix: #105 - 테이블뷰 삭제 오류 해결
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
Labels: bug

#111 초대 코드 조회하기 버튼 예외처리 외 기타 버그 수정
  Routory/Routory/Presentation/Home/View/ShareInviteCodeView.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/ShareInviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/MyPage/View/DeleteAccountModal.swift
  Routory/Routory/Presentation/MyPage/ViewController/AccountViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountFailModalViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/DeleteAccountModalViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/CopyButton.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/CopyButton.imageset/CopyButton.svg
Labels: bug

#108 근무 등록 화면 pop 관련 버그 수정
  Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Routory/Routory/Presentation/Components/BaseNavigationBar.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
Labels: bug

#112 Feat/#107
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Registration/Components/FieldRowView.swift
  Routory/Routory/Presentation/Registration/Components/LabelView.swift
  Routory/Routory/Presentation/Registration/Components/ValueRowView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Handler/ShiftRegistrationDelegateHandler.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/MemoBoxView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/RoutineView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkDateView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkPlaceSelectionView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkTimeView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkerSelectionView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/ShiftRegistrationContentView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/SalaryInfoView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkConditionView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkplaceInfoView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/WorkplaceRegistrationContentView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#114 하단 탭바 높이 변경
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/Calendar/CalendarSelected.imageset/CalendarSelected.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Calendar/CalendarUnselected.imageset/CalendarUnselected.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/HomeSelected.imageset/HomeSelected.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Home/HomeUnselected.imageset/HomeUnselected.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/MyPage/MyPageSelected.imageset/MyPageSelected.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/MyPage/MyPageUnselected.imageset/MyPageUnselected.svg
Labels: enhancement

#120 근무지 관련 로직 수정
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Entities/StoreCellInfo.swift
  Routory/Routory/Domain/Entities/WorkplaceCellInfo.swift
  Routory/Routory/Presentation/Home/View/Cell/MyStoreCell.swift
  Routory/Routory/Presentation/Home/View/Cell/MyWorkSpaceCell.swift
  Routory/Routory/Presentation/Home/View/HomeHeaderView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/Ellipsis/ellipsis.imageset/ellipsis.svg
Labels: enhancement

#125 feat: #121 - 수정 모드에서만 알바생 관리 보이게 하기
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/WorkplaceRegistrationContentView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceEditViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#128 근무지 수정 / 근무 수정
  Routory/Routory/Data/Repositories/CalendarRepository.swift
  Routory/Routory/Data/Repositories/WorkplaceRepository.swift
  Routory/Routory/Data/Services/CalendarService.swift
  Routory/Routory/Data/Services/UserService.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Interfaces/Repositories/CalendarRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/Repositories/WorkplaceRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/CalendarUseCaseProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/WorkplaceUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/CalendarUseCase.swift
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
Labels: enhancement

#130 루틴 관리 페이지 및 홈 내 오늘의 루틴 데이터 바인딩
  Routory/Routory/Domain/Entities/TodaysRoutine.swift
  Routory/Routory/Presentation/Home/View/Cell/MyStoreCell.swift
  Routory/Routory/Presentation/Home/View/Cell/MyWorkSpaceCell.swift
  Routory/Routory/Presentation/Home/View/HomeView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Routine/View/Cell/TodaysRoutineCell.swift
  Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewController/WorkplaceRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewModel/ManageRoutineViewModel.swift
  Routory/Routory/Presentation/Routine/ViewModel/WorkplaceRoutineViewModel.swift
Labels: enhancement

#131 미반영된 UI 및 로직 구현
  Routory/Routory/Common/Utils/Extensions/DateFormatter+Extension.swift
  Routory/Routory/Common/Utils/Extensions/NumberFormatter+Extension.swift
  Routory/Routory/Data/Services/EventService.swift
  Routory/Routory/Domain/Entities/Workplace.swift
  Routory/Routory/Presentation/Calendar/Model/CalendarModel.swift
  Routory/Routory/Presentation/Calendar/Model/FilterModel.swift
  Routory/Routory/Presentation/Calendar/Utils/BreakTimeMinutesDecimal.swift
  Routory/Routory/Presentation/Calendar/Utils/LabelColorString.swift
  Routory/Routory/Presentation/Calendar/View/CalendarView.swift
  Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
  Routory/Routory/Presentation/Calendar/View/Cell/EventCell.swift
  Routory/Routory/Presentation/Calendar/View/Cell/FilterCell.swift
  Routory/Routory/Presentation/Calendar/View/Components/CalendarEventVStackView.swift
  Routory/Routory/Presentation/Calendar/View/FilterView.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarEventListViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/CalendarEventListVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/FilterVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/YearMonthPickerVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/FilterViewController.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarEventListViewModel.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Routory/Routory/Presentation/Calendar/ViewModel/FilterViewModel.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
  Routory/Routory/Resources/Assets.xcassets/Icons/Ellipsis/Ellipsis.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Ellipsis/Ellipsis.imageset/Ellipsis.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Ellipsis/EventCellEllipsis.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Icons/Ellipsis/EventCellEllipsis.imageset/EventCellEllipsis.svg
  Routory/Routory/Resources/Assets.xcassets/Icons/Ellipsis/ellipsis.imageset/ellipsis.svg
Labels: enhancement

#132 삭제 전 확인 모달 뷰 구현
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/DeleteAlertViewController.swift
Labels: enhancement

#133 Feat/#129
  Routory/Routory/Data/Repositories/WorkplaceRepository.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/UseCases/WorkplaceUseCase.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/Handler/WorkplaceRegistrationDelegateHandler.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceEditViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerEditViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerListViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewModel/OwnerWorkplaceEditViewModel.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewModel/WorkerEditViewModel.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewModel/WorkerListViewModel.swift
Labels: enhancement

#141 근무지 삭제 버그 수정 / 리스너 버그 일부 수정 / 특정 근무지에 대한 컬러 값 불러오는 로직 구현
  Routory/Routory/Common/Utils/WageHelper.swift
  Routory/Routory/Data/Repositories/UserRepository.swift
  Routory/Routory/Data/Services/CalendarService.swift
  Routory/Routory/Data/Services/EventService.swift
  Routory/Routory/Data/Services/UserService.swift
  Routory/Routory/Data/Services/WorkplaceService.swift
  Routory/Routory/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/UserUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/UserUseCase.swift
Labels: bug, enhancement

#142 Feat/#137
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/WorkplaceRegistrationContentView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceEditViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/OwnerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewModel/WorkerWorkplaceRegistrationViewModel.swift
Labels: enhancement

#139 사장님 캘린더에서 근무 안보이는 현상 수정
  Routory/Routory/Data/Services/EventService.swift
  Routory/Routory/Domain/Entities/CalendarEvent.swift
  Routory/Routory/Domain/Entities/WorkerDetail.swift
  Routory/Routory/Domain/Entities/Workplace.swift
  Routory/Routory/Presentation/Calendar/Model/CalendarModel.swift
  Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
  Routory/Routory/Presentation/Calendar/View/Cell/EventCell.swift
  Routory/Routory/Presentation/Calendar/View/Components/CalendarEventVStackView.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/FilterViewController.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
Labels: bug

#144 전체 루틴 보기에서 루틴 수정하기
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/NewRoutine/ViewController/NewRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewController/ManageRoutineViewController.swift
  Routory/Routory/Presentation/Routine/ViewController/WorkplaceRoutineViewController.swift
Labels: enhancement

#150 Feat/#143
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewModel/ShiftEditViewModel.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#149 workplaceId 실제 데이터 받아오기
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
Labels: bug

#154 Feat/#151
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
Labels: enhancement

#147 라벨 색상 UI에 반영
  Routory/Routory/Data/Services/EventService.swift
  Routory/Routory/Domain/Entities/Workplace.swift
  Routory/Routory/Presentation/Calendar/Model/CalendarModel.swift
  Routory/Routory/Presentation/Calendar/Utils/LabelColorString.swift
  Routory/Routory/Presentation/Calendar/View/Cell/CalendarDayCell.swift
  Routory/Routory/Presentation/Calendar/View/Cell/EventCell.swift
  Routory/Routory/Presentation/Calendar/View/Components/CalendarEventVStackView.swift
  Routory/Routory/Presentation/Calendar/View/Components/ColorBorderView.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarEventListViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Routory/Routory/Presentation/Tabbar/ViewController/TabbarViewController.swift
Labels: enhancement

#156 로그인 화면 앱 로고 추가
  Routory/Routory/Presentation/Login/View/LoginView.swift
  Routory/Routory/Resources/Assets.xcassets/Images/Logo/AppTitle.imageset/AppTitle.svg
  Routory/Routory/Resources/Assets.xcassets/Images/Logo/AppTitle.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/Logo/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/Logo/Logo.imageset/Contents.json
  Routory/Routory/Resources/Assets.xcassets/Images/Logo/Logo.imageset/Logo-MOUP.svg
Labels: enhancement

#158 초대받은 근무지에서 근무가 보이지 않는 현상 수정
  Routory/Routory/Data/Services/EventService.swift
Labels: bug

#160 refactor: #155 - RepeatRow 숨김처리
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkDateView.swift
Labels: enhancement

#161 Home 화면에 들어갈 데이터 정제 로직 구현
  Routory/Routory.xcodeproj/project.pbxproj
  Routory/Routory/Common/Utils/PayrollCalculator.swift
  Routory/Routory/Common/Utils/TimeParser.swift
  Routory/Routory/Common/Utils/WorkTimeCalculator.swift
  Routory/Routory/Domain/Entities/StoreCellInfo.swift
  Routory/Routory/Domain/Entities/WorkerDetail.swift
  Routory/Routory/Domain/Entities/WorkplaceCellInfo.swift
  Routory/Routory/Presentation/Home/View/Cell/MyWorkSpaceCell.swift
  Routory/Routory/Presentation/Home/View/HomeFirstSectionCellRowView.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/InviteCodeViewController.swift
  Routory/Routory/Presentation/Home/ViewController/WorkplaceAddModalViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/HomeViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/ColorSelection/ViewController/ColorSelectionViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/Handler/WorkplaceRegistrationDelegateHandler.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkConditionView.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkerCell.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerListViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
Labels: enhancement

#162 25/6/27 심사 거부 대응
  Routory/Routory/Data/Repositories/UserRepository.swift
  Routory/Routory/Data/Services/EventService.swift
  Routory/Routory/Data/Services/UserService.swift
  Routory/Routory/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
  Routory/Routory/Domain/Interfaces/UseCases/UserUseCaseProtocol.swift
  Routory/Routory/Domain/UseCases/UserUseCase.swift
  Routory/Routory/Presentation/Calendar/View/CalendarEventListView.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarEventListViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/CalendarViewController.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/CalendarEventListVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewController/Delegates/RegistrationVCDelegate.swift
  Routory/Routory/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Routory/Routory/Presentation/Components/DeleteAlertViewController.swift
  Routory/Routory/Presentation/Home/ViewController/HomeViewController.swift
  Routory/Routory/Presentation/Home/ViewModel/InviteCodeViewModel.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/Submodules/ColorSelection/ViewController/ColorSelectionViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/Components/WorkDateView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/View/ShiftRegistrationContentView.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/OwnerShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/ShiftRegistration/ViewController/WorkShiftRegistrationViewController.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/View/Components/WorkerCell.swift
  Routory/Routory/Presentation/Registration/WorkplaceRegistration/ViewController/WorkerWorkplaceRegistrationViewController.swift
  Routory/Routory/Presentation/TabBar/ViewController/TabBarViewController.swift
  Routory/Routory/Resources/Version.xcconfig
Labels: bug, documentation

#170 로그아웃 확인 모달 구현
  Routory/Routory/Presentation/Components/DeleteAlertViewController.swift
  Routory/Routory/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: enhancement
